name: uat
on:
  push:
    branches:
      - uat
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.0.0"
      - name: yarn
        run: yarn
      - name: copy file  via ssh key
        uses: appleboy/scp-action@master
        with:
          source: "./*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/uat/abstract-egg/"
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /usr/src/zhoubichuan/uat/abstract-egg
            export NODE_HOME=/usr/bin/node
            export PATH=$PATH:$NODE_HOME/bin
            yarn install
            yarn add pm2
            pm2 delete abstract-egg
            pm2 start --name abstract-egg yarn -- run dev
